project:
  type: website

website:
  title: "From The Desk of Rylyn"
  site-url: https://github.com/RylynWill/DeskOfRylyn.git
  
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

